### ISSUE TITLE
Where is the Wiki?

### ISSUE THREAD

**Issue by Halnex** [PHPSocialverse/PHPSocialverse#1]
So where is the wiki?

And your site is giving a blank page.

**Comment by PHPJosh** [comment]
Sorry for any confusion before as I may have gotten ahead of myself. ATM there is still alot of code I have not pushed to the repo yet as there is alot of things I am still debating and testing and will be pushing all my updated code soon. The script is still very early in development and things are changing quite constantly on my end. Once I have some things sorted soon I will update the wiki with quite a bit of info like how to write addon's as it will be  extensible  and also will be providing coding examples, Folder structures, how Models, Controllers, and theming and such works. which atm the Themes are  what I am focused on and setting up Default CSS and JS setup . once I get that code done will be pushing that here. but honestly just got a little ahead of myself as far as the wiki goes and changed the Read Me to reflect that. also will be changing the wiki home to reflect it also. sorry for any confusion  but PHPSocialverse is going to be quite extensive and will take quite a bit longer to start getting the basics covered in the wiki, But I will start updating the wiki as I push code so other can be informed as we go :)

**Comment by Halnex** [comment]
Thank you for your reply.
I look forward to it, and I hope it's easy to create or edit modules.

I've checked your folder structure, it looks a bit different. Each module has its own filters, services...
so I'm hoping it won't be complicated.

**Comment by PHPJosh** [comment]
The Modules Folder structure will be refined as we go so many of those folders probably will not be there in the final 1.0.0 release or maybe sooner than it. for now I just have it  like this  for testing purposes. But each module will have its owns Filters,Controllers and Routes like a normal Laravel app.. but the goal is to make all this as simple as possible and yet Powerful
