### ISSUE TITLE
issue with install process

### ISSUE THREAD

**Issue by ghost** [PHPSocialverse/PHPSocialverse#2]
issue after it asks for database information 
do you have a sql dump of your db table schema?
(below is the error that is shown on screen)
(1st attempt)
Whoops, looks like something went wrong.

1/1
FatalErrorException in OutputFormatter.php line 181:
Maximum execution time of 120 seconds exceeded

(2nd attempt)
Whoops, looks like something went wrong.

1/1
FatalErrorException in HandleExceptions.php line 59:
Maximum execution time of 120 seconds exceeded

**Comment by PHPJosh** [comment]
alright will take a look at this and figure this out. going to upload to one of my webservers.  and test it. and nope I don't have a sql dump. will install on Homestead later and fill it out with some generic data and dump the database.

atm the install uses Laravels Database Migrations  http://laravel.com/docs/5.1/migrations  to install the database as it easy to setup on the different database drivers the script uses thus far, Mysql, Pgsql and MSSQL. 

sounds like I need the Install to ajust certain php.ini settings just for the install on certain servers or I need the break the the migrations into steps

**Comment by illuminati8614** [comment]
yeah ok no problems, i just really want to test it so i can make a theme

**Comment by PHPJosh** [comment]
also maybe you should have a look here http://laravel.com/docs/5.1/homestead this is what I am using for development atm and depending on your OS is a pretty simple setup and would be a quick start to getting a development environment up and running in the mean time. but if you on windows this can be a pain to setup. IMO windows lacks alot as far as web development when it comes to techs outside of Microsoft. I will post again though once I have further info on this fix though

**Comment by PHPJosh** [comment]
This Is fixed and install is working correctly now

**Comment by stewie27** [comment]
install is working but got a error after logging in.

this is the log file content

[2015-09-26 18:23:39] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Core\Http\Widgets\BaseWidget' not found' in C:\wamp\www\modules\User\Http\Widgets\UserInfo.php:10
Stack trace:
#0 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 C:\wamp\www\lib\Vendor\composer\ClassLoader.php(412): ()
#4 C:\wamp\www\lib\Vendor\composer\ClassLoader.php(301): Composer\Autoload\includeFile()
#5 C:\wamp\www\lib\PHPSocialverse\Widgets\WidgetFactory.php(0): Composer\Autoload\ClassLoader->loadClass()
#6 C:\wamp\www\lib\PHPSocialverse\Widgets\WidgetFactory.php(52): spl_autoload_call()
#7 C:\wamp\www\lib\PHPSocialverse\Widgets\WidgetFactory.php(52): class_exists()
#8 C:\wamp\www\lib\PHPSocialverse\Widgets\WidgetFactory.php(86): Lib\PHPSocialverse\Widgets\WidgetFactory->determineNamespace()
#9 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(210): Lib\PHPSocialverse\Widgets\WidgetFactory->run()
#10 C:\wamp\www\file\framework\views\60d5826492138ff6f6eb2c746b337632(23): Illuminate\Support\Facades\Facade::__callStatic()
#11 C:\wamp\www\file\framework\views\60d5826492138ff6f6eb2c746b337632(23): Lib\PHPSocialverse\Widgets\Facades\Widget::run()
#12 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(42): ()
#13 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(58): Illuminate\View\Engines\PhpEngine->evaluatePath()
#14 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\View\View.php(138): Illuminate\View\Engines\CompilerEngine->get()
#15 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\View\View.php(107): Illuminate\View\View->getContents()
#16 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->renderContents()
#17 C:\wamp\www\lib\PHPSocialverse\Theme\Theme.php(1412): Illuminate\View\View->render()
#18 C:\wamp\www\modules\Core\Http\Controllers\IndexController.php(56): Lib\PHPSocialverse\Theme\Theme->render()
#19 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): Modules\Core\Http\Controllers\IndexController->index()
#20 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\Controller.php:256}()
#21 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction()
#22 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call()
#23 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}()
#24 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}()
#25 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()
#27 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then()
#28 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack()
#29 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\Route.php(201): Illuminate\Routing\ControllerDispatcher->dispatch()
#30 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher()
#31 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\Router.php(704): Illuminate\Routing\Route->run()
#32 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#33 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}()
#34 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()
#36 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\Router.php(706): Illuminate\Pipeline\Pipeline->then()
#37 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\Router.php(671): Illuminate\Routing\Router->runRouteWithinStack()
#38 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Routing\Router.php(631): Illuminate\Routing\Router->dispatchToRoute()
#39 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router->dispatch()
#40 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#41 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:139}()
#42 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#44 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#45 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#47 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#48 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Session\Middleware\StartSession->handle()
#50 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#51 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#53 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#54 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#56 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#57 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#59 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:124}()
#60 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func:{C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:103}()
#62 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then()
#63 C:\wamp\www\lib\Vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#64 C:\wamp\www\index.php(77): Illuminate\Foundation\Http\Kernel->handle()
#65 C:\wamp\www\index.php(0): {main}()
#66 {main}

**Comment by PHPJosh** [comment]
Yep that was a bug with that Commit as that was right after I turned the Core Namespace into a Module. Try redownloading the branch and reupload as i did catch that and fixed it
